global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cloudgames-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5143']
      - targets: ['3.89.91.160:8080']