{
 "title": "Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Visão geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"cloudgames-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de scrape (seg) – sanity check do Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{job=\"cloudgames-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RPS por método",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"cloudgames-api\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"cloudgames-api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erros 5xx (rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"cloudgames-api\", code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx vs 5xx (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"cloudgames-api\", code=~\"4..\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_received_total{job=\"cloudgames-api\", code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latência", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "p95 (seg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"cloudgames-api\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 (mediana)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"cloudgames-api\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}